[Quiz] A, B반이 있고, 각각 10명의 학생이 있는데, id는 0 ~ 9이다.

1. seed를 123으로 고정하고 kor, math, sci 3개의 과목에 대한 점수를 생성한다.
- 점수는 [30, 101] 사이에서 생성한다.
2. 반별로 과목별 고점자의 id를 추출하자.
3. 반별로 평균점수의 고점자 순으로 5명씩 추출하자.

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(123)
scores = np.random.randint(30,101, (2,10,3))
scores

array([[[ 96,  47,  87],
        [ 77,  62,  76],
        [ 55,  66,  98],
        [ 79,  85,  97],
        [ 32,  69,  96],
        [ 77,  91,  78],
        [ 37,  82,  57],
        [ 64,  70,  33],
        [ 99,  94,  64],
        [ 88,  40,  52]],

       [[ 48,  45,  57],
        [ 60,  82, 100],
        [ 56,  36,  44],
        [ 84,  31,  73],
        [ 88,  85,  55],
        [ 80,  86,  79],
        [ 42,  48,  31],
        [ 81,  74,  78],
        [ 86,  79,  33],
        [ 97,  41,  51]]])

In [3]:
highscores = scores.max(1)
highscores

array([[ 99,  94,  98],
       [ 97,  86, 100]])

In [4]:
highscoreIDs = scores.argmax(1)
highscoreIDs

array([[8, 8, 2],
       [9, 5, 1]], dtype=int64)

In [5]:
meanscores = scores.mean(2)
meanscores

array([[76.66666667, 71.66666667, 73.        , 87.        , 65.66666667,
        82.        , 58.66666667, 55.66666667, 85.66666667, 60.        ],
       [50.        , 80.66666667, 45.33333333, 62.66666667, 76.        ,
        81.66666667, 40.33333333, 77.66666667, 66.        , 63.        ]])

In [6]:
meanscores.argsort(-1)

array([[7, 6, 9, 4, 1, 2, 0, 5, 8, 3],
       [6, 2, 0, 3, 9, 8, 4, 7, 1, 5]], dtype=int64)

In [7]:
top5ID = meanscores.argsort(-1)[:, -1:-6:-1]
top5ID

array([[3, 8, 5, 0, 2],
       [5, 1, 7, 4, 8]], dtype=int64)